"""Type stubs for ironforest._core module."""

from typing import Optional, TypeVar, Generic, Sequence, Iterator, List, Literal, Tuple, overload, Any, Union

T_co = TypeVar("T_co", covariant=True)

ArrayLike = Union['Array', Sequence[float], Sequence[Sequence[float]], float, int, Any]
Dtype = Literal["float", "float64", "f64", "int", "int64", "i64"]


class TaskType:
    """Task type for tree algorithms."""

    @staticmethod
    def classification() -> TaskType: ...

    @staticmethod
    def regression() -> TaskType: ...

    @staticmethod
    def anomaly_detection() -> TaskType: ...

    def __repr__(self) -> str: ...


class SplitCriterion:
    """Criterion for evaluating splits."""

    @staticmethod
    def gini() -> SplitCriterion: ...

    @staticmethod
    def entropy() -> SplitCriterion: ...

    @staticmethod
    def mse() -> SplitCriterion: ...

    @staticmethod
    def random() -> SplitCriterion: ...

    @staticmethod
    def random_projection() -> SplitCriterion: ...

    def __repr__(self) -> str: ...


class TreeConfig:
    """Configuration for a single decision tree."""

    def __init__(
        self,
        task_type: TaskType,
        n_classes: int = 2,
        max_depth: Optional[int] = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
        max_features: Optional[int] = None,
        criterion: Optional[SplitCriterion] = None,
        seed: int = 42,
        projection_type = None,
        projection_density = None,
    ) -> None: ...

    @staticmethod
    def classification(n_classes: int) -> TreeConfig: ...

    @staticmethod
    def regression() -> TreeConfig: ...

    @staticmethod
    def isolation(max_samples: int) -> TreeConfig: ...

    @property
    def max_depth(self) -> Optional[int]: ...
    @max_depth.setter
    def max_depth(self, value: Optional[int]) -> None: ...

    @property
    def min_samples_split(self) -> int: ...
    @min_samples_split.setter
    def min_samples_split(self, value: int) -> None: ...

    @property
    def min_samples_leaf(self) -> int: ...
    @min_samples_leaf.setter
    def min_samples_leaf(self, value: int) -> None: ...

    @property
    def max_features(self) -> Optional[int]: ...
    @max_features.setter
    def max_features(self, value: Optional[int]) -> None: ...

    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

    def __repr__(self) -> str: ...


class Tree:
    """A single decision tree."""

    @staticmethod
    def fit(
        config: TreeConfig,
        data: object,
        labels: object,
        n_samples: int,
        n_features: int,
    ) -> Tree: ...

    def predict(
        self,
        data: object,
        n_samples: int,
    ) -> object: ...

    def predict_anomaly_scores(
        self,
        data: object,
        n_samples: int,
    ) -> object: ...

    def predict_path_lengths(
        self,
        data: object,
        n_samples: int,
    ) -> object: ...

    @property
    def n_nodes(self) -> int: ...

    @property
    def n_features(self) -> int: ...

    @property
    def max_depth_reached(self) -> int: ...

    @property
    def n_training_samples(self) -> int: ...

    def __repr__(self) -> str: ...


class EnsembleConfig:
    """Configuration for an ensemble of trees."""

    def __init__(
        self,
        n_trees: int,
        tree_config: TreeConfig,
        bootstrap: bool = True,
        max_samples: Optional[int] = None,
        seed: int = 42,
    ) -> None: ...

    @staticmethod
    def random_forest_classifier(n_trees: int, n_classes: int) -> EnsembleConfig: ...

    @staticmethod
    def random_forest_regressor(n_trees: int) -> EnsembleConfig: ...

    @staticmethod
    def isolation_forest(n_trees: int, max_samples: int) -> EnsembleConfig: ...

    @property
    def n_trees(self) -> int: ...
    @n_trees.setter
    def n_trees(self, value: int) -> None: ...

    @property
    def bootstrap(self) -> bool: ...
    @bootstrap.setter
    def bootstrap(self, value: bool) -> None: ...

    @property
    def max_samples(self) -> Optional[int]: ...
    @max_samples.setter
    def max_samples(self, value: Optional[int]) -> None: ...

    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

    def __repr__(self) -> str: ...


class Ensemble:
    """An ensemble of decision trees."""

    @staticmethod
    def fit(
        config: EnsembleConfig,
        data: object,
        labels: object,
        n_samples: int,
        n_features: int,
    ) -> Ensemble: ...

    def predict(
        self,
        data: object,
        n_samples: int,
    ) -> object: ...

    @property
    def n_trees(self) -> int: ...

    @property
    def n_training_samples(self) -> int: ...

    def __repr__(self) -> str: ...


class Array(Sequence[T_co], Generic[T_co]):
    """N-dimensional array of float64 or int64 values."""

    def __init__(self, shape: Sequence[int], data: Sequence[float] | Sequence[int], dtype: Dtype | None = None) -> None:
        """Create array from shape and flat data list."""
        ...

    @property
    def dtype(self) -> Literal["float64", "int64"]:
        """The element type of this array."""
        ...

    @staticmethod
    def zeros(shape: Sequence[int], dtype: Dtype | None = None) -> Array:
        """Create array filled with zeros."""
        ...

    @staticmethod
    def ones(shape: Sequence[int], dtype: Dtype | None = None) -> Array:
        """Create array filled with ones."""
        ...

    @staticmethod
    def full(shape: Sequence[int], fill_value: float, dtype: Dtype | None = None) -> Array:
        """Create array filled with a specified value."""
        ...

    @staticmethod
    def asarray(data: ArrayLike, shape: Sequence[int] | None = None, dtype: Dtype | None = None) -> Array:
        """Create array from data with optional reshape."""
        ...

    @staticmethod
    def eye(n: int, m: int | None = None, k: int | None = None, dtype: Dtype | None = None) -> Array:
        """Create a 2D identity matrix with ones on the k-th diagonal."""
        ...

    @staticmethod
    def diag(v: ArrayLike, k: int | None = None) -> Array:
        """Create a 2D array with v on the k-th diagonal."""
        ...

    @property
    def shape(self) -> List[int]:
        """Get the shape as a list."""
        ...

    @property
    def ndim(self) -> int:
        """Get the number of dimensions."""

    def get(self, indices: Sequence[int]) -> float | int:
        """Get element at indices."""
        ...

    def tolist(self) -> list:
        """Return data as nested Python list (floats or ints depending on dtype)."""
        ...

    def diagonal(self, k: int | None = None) -> Array:
        """Extract the k-th diagonal from a 2D array."""
        ...

    def transpose(self) -> Array:
        """Transpose a 2D matrix."""
        ...

    def t(self) -> Array:
        """Transpose (alias for transpose())."""
        ...

    def ravel(self) -> Array:
        """Flatten the array to 1D (returns a copy)."""
        ...

    def take(self, indices: Sequence[int]) -> Array:
        """Take elements from the array at specified flat indices."""
        ...

    def reshape(self, shape: Sequence[int]) -> Array:
        """Return a view of the array with a new shape."""
        ...

    def item(self) -> float | int:
        """Convert a single-element array into a Python scalar (float or int)."""
        ...

    def to_numpy(self) -> Any:
        """Convert this Array to a numpy ndarray."""
        ...

    def matmul(self, other: Array) -> Array[float]:
        """Matrix multiplication."""
        ...

    def dot(self, other: Array) -> Array[float]:
        """Dot/matrix product."""
        ...

    def __matmul__(self, other: Array) -> Array[float]:
        """Matrix multiplication operator (@)."""
        ...

    def sin(self) -> Array[float]: ...
    def cos(self) -> Array[float]: ...
    def tan(self) -> Array[float]: ...
    def arcsin(self) -> Array[float]: ...
    def arccos(self) -> Array[float]: ...
    def arctan(self) -> Array[float]: ...
    def exp(self) -> Array[float]: ...
    def sqrt(self) -> Array[float]: ...
    def log(self) -> Array[float]:
        """Natural logarithm, element-wise."""
        ...
    def abs(self) -> Array:
        """Absolute value, element-wise."""
        ...
    def sign(self) -> Array:
        """Returns -1, 0, or 1 for each element based on sign."""
        ...
    def clip(self, min: float, max: float) -> Array: ...

    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def var(self) -> float: ...
    def std(self) -> float: ...
    def median(self) -> float: ...
    def max(self) -> float: ...
    def min(self) -> float: ...
    @overload
    def quantile(self, q: float) -> float: ...
    @overload
    def quantile(self, q: ArrayLike) -> Array[float]: ...

    def any(self) -> bool: ...
    def all(self) -> bool: ...

    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> float | int | Array: ...
    @overload
    def __getitem__(self, index: slice) -> Array: ...
    @overload
    def __getitem__(self, index: List[bool]) -> Array: ...
    @overload
    def __getitem__(self, index: Tuple[int, int]) -> float | int: ...
    @overload
    def __getitem__(self, index: Tuple[int, slice]) -> Array: ...
    @overload
    def __getitem__(self, index: Tuple[slice, int]) -> Array: ...
    @overload
    def __getitem__(self, index: Tuple[slice, slice]) -> Array: ...
    @overload
    def __getitem__(self, index: Tuple[int, ...]) -> float | int | Array: ...
    @overload
    def __setitem__(self, index: int, value: float | int) -> None: ...
    @overload
    def __setitem__(self, index: Tuple[int, ...], value: float | int) -> None: ...
    def __iter__(self) -> Iterator[float | int]: ...
    def __contains__(self, value: float | int) -> bool: ...

    def __add__(self, other: ArrayLike) -> Array: ...
    def __radd__(self, other: float | int) -> Array: ...
    def __sub__(self, other: ArrayLike) -> Array: ...
    def __rsub__(self, other: float | int) -> Array: ...
    def __mul__(self, other: ArrayLike) -> Array: ...
    def __rmul__(self, other: float | int) -> Array: ...
    def __truediv__(self, other: ArrayLike) -> Array: ...
    def __rtruediv__(self, other: float | int) -> Array: ...
    def __neg__(self) -> Array: ...
    def __pow__(self, exp: ArrayLike, modulo: None = None) -> Array: ...
    def __rpow__(self, base: float | int, modulo: None = None) -> Array: ...
    def __lt__(self, other: ArrayLike) -> Array: ...
    def __le__(self, other: ArrayLike) -> Array: ...
    def __gt__(self, other: ArrayLike) -> Array: ...
    def __ge__(self, other: ArrayLike) -> Array: ...
    def __eq__(self, other: ArrayLike) -> Array: ...  # type: ignore[override]
    def __ne__(self, other: ArrayLike) -> Array: ...  # type: ignore[override]
    def __repr__(self) -> str: ...


from . import linalg as linalg
from . import stats as stats
from . import random as random
from . import ndutils as ndutils
from . import spatial as spatial
